/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import module java.base;

public class App {

    public static void main(String[] args) {
        int porta = 1234;
        String host = "localhost";

        if (args.length == 2) {
            host = args[0];
            porta = Integer.parseInt(args[1]);
        }

        try (
             var socket = new Socket(host, porta);
             var reader = new BufferedReader(
                     new InputStreamReader(socket.getInputStream(), StandardCharsets.UTF_8)
             );
             var writer = new BufferedWriter(
                     new OutputStreamWriter(socket.getOutputStream(), StandardCharsets.UTF_8)
             )
        ){
            IO.println("Conectando no servidor...");

            writer.write("Olá! Eu sou o cliente.");
            writer.newLine();
            writer.flush();

            String resposta = reader.readLine();

            System.out.printf("Resposta do servidor: %s%n", resposta);
            IO.println("Cliente finalizado");

        } catch (Exception e) {
            System.err.println("Erro: " + e);
        }

    }
}
