services:
  redis:
    image: redis:alpine

  webapp:
    build: .
    ports:
      - 5000
    volumes:
      - ./app:/app
    deploy:
      replicas: 3
    
  caddy:
    image: caddy:alpine
    ports:
      - 4000:4000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile