/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import module java.base;

public class App {

    public static void main(String[] args) {

        int porta = 1234;
        IO.println("..:: Servidor de Arquivos ::..");

        // Cria o socket em uma porta
        try(ServerSocket serverSocket = new ServerSocket(porta)) {
            IO.println("Aguardando conexões...");

            while (!Thread.currentThread().isInterrupted()) {
                Socket clientSocket = serverSocket.accept(); // Aguarda uma conexão
                Thread.ofVirtual().start(new AtenderCliente(clientSocket));
            }

        } catch (Exception e) {
            System.err.println("Erro: " + e);
        }
    }
}
