/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import module java.base;

public class App {

    public static void main(String[] args) {

        int porta = 1234;
        IO.println("..:: Servidor ::..");

        // Cria o socket em uma porta
        try(ServerSocket serverSocket = new ServerSocket(porta)) {
            IO.println("Aguardando conexões...");

            // Aguarda uma conexão
            Socket clientSocket = serverSocket.accept();

            // Obtém os dados do cliente
            var enderecoCliente = clientSocket.getInetAddress().getHostAddress();
            var portaCliente = clientSocket.getPort();
            System.out.printf("Cliente conectado: %s: %d%n", enderecoCliente, portaCliente);

            // Estabelecimentos dos fluxos de entrada e saída
            var reader = new BufferedReader(
                    new InputStreamReader(clientSocket.getInputStream(), StandardCharsets.UTF_8)
            );
            var writer = new BufferedWriter(
                    new OutputStreamWriter(clientSocket.getOutputStream(), StandardCharsets.UTF_8)
            );

            // Protocolo de comunicação
            String mensagem = reader.readLine();

            System.out.printf("[%s:%d] -> %s%n", enderecoCliente, portaCliente, mensagem);

            writer.write(mensagem.toUpperCase());
            writer.newLine();
            writer.flush();

            IO.println("Servidor encerrado!");
            reader.close();
            writer.close();

        } catch (Exception e) {
            System.err.println("Erro: " + e);
        }

    }
}
